amcl:
  ros__parameters:
    use_sim_time: True
    
    # 优化里程计噪声模型 (降为原值1/4)
    alpha1: 0.05   # X/Y平移噪声
    alpha2: 0.02   # X/Y平移噪声 (旋转干扰)
    alpha3: 0.08   # 旋转噪声 (平移干扰)
    alpha4: 0.03   # 纯旋转噪声
    alpha5: 0.08   # 附加平移噪声
    
    base_frame_id: "base_footprint"
    
    # 光束跳过参数 (保持默认)
    beam_skip_distance: 0.4
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    
    global_frame_id: "map"
    lambda_short: 0.1
    
    # 增大激光似然场范围 (提升全局特征)
    laser_likelihood_max_dist: 5.0  # 从2.0增加
    
    laser_max_range: 100.0
    laser_min_range: 0.1
    laser_model_type: "likelihood_field"
    
    # 提升扫描利用率 (加倍光束)
    max_beams: 120  # 从60增加
    
    # 调整粒子范围并启用恢复机制
    max_particles: 3000    # 从2000增加
    min_particles: 800     # 从500增加
    recovery_alpha_fast: 0.001  # 启用快速恢复
    recovery_alpha_slow: 0.0001 # 启用慢速恢复
    
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    
    # 减小变换容差 (提高实时性)
    transform_tolerance: 0.2  # 从0.5减少
    
    # 降低更新阈值 (更频繁更新)
    update_min_a: 0.03   # 从0.06减半 (弧度)
    update_min_d: 0.01   # 从0.025减少 (米)
    
    # 优化传感器模型权重
    z_hit: 0.85    # 增加命中权重
    z_rand: 0.05   # 稍减随机噪声
    z_short: 0.1   # 降低短距误检影响
    
    scan_topic: /scan
    set_initial_pose: True
    initial_pose.x: 0.0
    initial_pose.y: 0.0
    initial_pose.z: 0.0
    initial_pose.yaw: 0.0

    #Amcl参数解释参考：https://docs.nav2.org/configuration/packages/configuring-amcl.html

amcl_map_client:
  ros__parameters:
    use_sim_time: True

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: True

bt_navigator:
  ros__parameters:
    use_sim_time: True
    transform_tolerance: 0.1 #变换容差
    goal_reached_tol: 0.6 #接受姿势作为目标的容忍度(m)
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: odom
    bt_loop_duration: 10        #BT 执行每次迭代的持续时间（以毫秒为单位
    default_server_timeout: 20  #BT 操作节点等待操作服务器确认时的默认超时值（以毫秒为单位）
    
    error_code_names:
    - compute_path_error_code 
    - follow_path_error_code
# bt_navigator参数说明：https://docs.nav2.org/configuration/packages/configuring-bt-navigator.html?highlight=bt_navigator

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: True



controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 50.0                
    min_x_velocity_threshold: 0.0           
    # min_x_velocity_threshold: 0.295           
    min_y_velocity_threshold: 0.0             
    min_theta_velocity_threshold: 0.1       
    odom_topic: odom
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.6            
      movement_time_allowance: 8.0            
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.3                  
      yaw_goal_tolerance: 1.0                 
      stateful: True
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.7                          
      lookahead_dist: 1.0                               
      min_lookahead_dist: 0.3                          
      max_lookahead_dist: 0.6                          
      lookahead_time: 1.5                              
      rotate_to_heading_angular_vel: 0.4               #如果使用旋转至航向，则这是要使用的角速度。
      transform_tolerance: 0.1                         #TF 变换容差
      use_velocity_scaled_lookahead_dist: true        #是否使用速度缩放的前瞻距离或常数lookahead_distance
      min_approach_linear_velocity: 0.5               # 接近目标时应用的最小速度阈值
      approach_velocity_scaling_dist: 1.0              # 距离变换路径末端的积分距离，在此距离处开始应用速度缩放。
      #注意：默认为代价地图的前向范围减去一个代价地图单元长度。
      use_collision_detection: true                    #是否启用碰撞检测。

      max_allowed_time_to_collision_up_to_carrot: 0.5  #use_collision_detection为真，投射速度命令以检查碰撞的时间true。它被限制为所选前瞻距离的最大距离。
      use_regulated_linear_velocity_scaling: true      #是否使用受控的曲率特征
      use_cost_regulated_linear_velocity_scaling: true #是否使用受管制的接近障碍物功能
      regulated_linear_scaling_min_radius: 0.4         #触发调节功能的转弯半径。请记住，转弯越急，半径就越小
      regulated_linear_scaling_min_speed: 0.25         #受调节特征能够发送的最小速度，以确保即使在高曲率的高成本空间中仍可实现过程。
      use_rotate_to_heading: false                      # 使用完整规划器时是否启用旋转到粗略航向和目标方向。
      rotate_to_heading_min_angle: 0.785               #use_rotate_to_heading如果启用，则路径方向和起始机器人方向之间的差异将触发原地旋转。
      max_angular_accel: 1.0                           #旋转至航向时允许的最大角加速度（如果启用）
      max_robot_pose_search_dist: 1.0                 #沿路径搜索最接近机器人姿势的最大综合距离。#-->10.0
      #注意：默认设置为最大代价地图范围，因此除非本地代价地图内存在循环，否则不应手动设置。
      use_interpolation: true                         #启用路径上姿势之间的插值以进行前瞻点选择。帮助稀疏路径避免引起不连续的指令速度。
      cost_scaling_dist: 0.1 #use_cost_regulated_linear_velocity_scaling如果启用，则触发线速度缩放的最小障碍物距离。
      #注意：设置的值应小于或等于inflation_radiuscostmap 膨胀层中设置的值，因为膨胀用于计算与障碍物的距离
      cost_scaling_gain: 0.8 #乘数增益应小于或等于 1.0，用于在 范围内有障碍物时进一步调整速度cost_scaling_dist。
      #注意：值越低，减速越快。
      inflation_cost_scaling_factor: 5.0               #局部代价地图中膨胀层设置的值cost_scaling_factor。
      #注意：该值应与使用膨胀单元格值准确计算与障碍物的距离完全相同
      goal_dist_tol: 0.3
      # 不允许倒车
      allow_reversing: True  
      #参数参考：https://github.com/ros-navigation/navigation2/blob/humble/nav2_regulated_pure_pursuit_controller/README.md
      
controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0  #成本地图更新频率
      publish_frequency: 10.0 #将成本图发布到话题的频率
      global_frame: odom      #全局框架
      robot_base_frame: base_footprint #机器人底座框架
      use_sim_time: True  #仿真时间
      rolling_window: true #成本地图是否应随机器人基座框架滚动
      width: 4             #代价地图的宽度（m）
      height: 4            #代价地图的高度（m）
      resolution: 0.05     #代价地图1像素的分辨率，以米为单位
      robot_radius: 0.60   #机器人半径，如果未提供足迹坐标，则使用机器人半径。
      footprint: "[ [-0.32, -0.18], [-0.32, 0.18], [0.32,0.18], [0.32, -0.18] ]"
      plugins: ["voxel_layer","inflation_layer"] #插件包括:{“体素层”，“障碍层”，“膨胀层”}
      inflation_layer:                             #膨胀层参数
        plugin: "nav2_costmap_2d::InflationLayer"  #膨胀层插件。
        cost_scaling_factor: 5.0                   #成本缩放因子，决定障碍物成本随距离的递减速度。
        inflation_radius: 0.6                     #膨胀半径
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"      #体素层插件。
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0                              #体素地图的起始Z坐标
        z_resolution: 0.05                         #体素地图的Z轴分辨率
        z_voxels: 16                               #体素地图的Z轴体素数量
        max_obstacle_height: 2.0                   #可检测障碍物的最大高度（米）
        mark_threshold: 0                          #标记体素的阈值
        observation_sources: scan                  #观测源
        scan:
          topic: /scan
          max_obstacle_height: 2.0                  #可检测障碍物的最大高度（米）
          clearing: True                            #是否启用障碍物清除功能
          marking: True                             #是否启用障碍物标记功能
          data_type: "LaserScan"                    #数据类型
          raytrace_max_range: 10.0                  #控制光线追踪从代价地图中清除障碍物的最大范围 
          raytrace_min_range: 0.0                  #控制光线追踪从代价地图中清除障碍物的最大范围 
          obstacle_max_range: 2.5                   #控制代价地图上标记障碍物的最大范围
          obstacle_min_range: 0.1                   #控制代价地图上标记障碍物的最小范围

      always_send_full_costmap: False                 #是否每次更新时都发送完整的成本图，而不是更新
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 10.0             #成本地图更新频率
      publish_frequency: 10.0            #将成本图发布到话题的频率
      global_frame: map                 #全局框架
      robot_base_frame: base_footprint  #机器人底座框架
      use_sim_time: True               #仿真时间 
      robot_radius: 0.60                #机器人半径
      footprint: "[ [-0.32, -0.18], [-0.32, 0.18], [0.32,0.18], [0.32, -0.18] ]"
      resolution: 0.2                  #全局地图1像素的分辨率，以米为单位
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"] #插件包括：{“静态层”，“障碍层”，“膨胀层”}
      obstacle_layer:  #障碍层参数
        plugin: "nav2_costmap_2d::ObstacleLayer" #障碍层插件
        enabled: True
        observation_sources: scan                  #观测源
        scan:
          topic: scan
          max_obstacle_height: 2.0                 #可检测障碍物的最大高度（米）
          clearing: True                           #是否启用障碍物清除功能
          marking: True                            #是否启用障碍物标记功能
          data_type: "LaserScan"                   #数据类型
          raytrace_max_range: 10.0                 #控制光线追踪从代价地图中清除障碍物的最大范围 
          raytrace_min_range: 0.0                  #控制光线追踪从代价地图中清除障碍物的最大范围 
          obstacle_max_range: 2.5                  #控制代价地图上标记障碍物的最大范围
          obstacle_min_range: 0.1                  #控制代价地图上标记障碍物的最小范围
      static_layer: #静态层参数
        plugin: "nav2_costmap_2d::StaticLayer"     #静态层插件
        map_subscribe_transient_local: True
      inflation_layer: #膨胀层参数
        plugin: "nav2_costmap_2d::InflationLayer"  #膨胀层插件
        cost_scaling_factor: 5.0                   #成本缩放因子，决定障碍物成本随距离的递减速度。
        inflation_radius: 0.6                     #膨胀半径
      always_send_full_costmap: True               #是否每次更新时都发送完整的成本图，而不是更新
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "map_out.yaml"

map_saver:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 5.0                #尝试保存地图的超时时间（秒）
    free_thresh_default: 0.25            #占用网格的自由空间最大概率阈值
    occupied_thresh_default: 0.65        #占用网格的占用空间最小概率阈值
    map_subscribe_transient_local: True  #地图话题的 QoS 设置

planner_server: #规划器服务器参数
  ros__parameters:
    planner_plugins: ["GridBased"]
    use_sim_time: True
    expected_planner_frequency: 1.0     #预期的规划器频率。如果当前频率小于预期频率，则显示警告消息。
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid" #Smac Hybrid-A* 规划器
      tolerance: 0.1                      # 如果无法达到精确的姿势，则规划的容差(单位m)
      downsample_costmap: false           # 是否将代价图下采样至另一个分辨率以进行搜索
      downsampling_factor: 1              # 对代价图进行下采样的乘数因子
      allow_unknown: false                # 允许在未知空间搜索
      max_iterations: 1000000             # 失败前搜索的最大迭代次数（以防无法到达），设置为 -1 以禁用
      max_on_approach_iterations: 1000    # 在公差范围内尝试达到目标的最大迭代次数，仅限 2D
      max_planning_time: 7.0              # 规划器进行规划、平滑和上采样的最大时间（以秒为单位）。
      motion_model_for_search: "DUBIN"  # 2D Moore, Von Neumann; Hybrid Dubin, Redds-Shepp; State Lattice set internally
      cost_travel_multiplier: 10.0         #应用于搜索以避开高成本区域的成本乘数。
      # For 2D: Cost multiplier to apply to search to steer away from high cost areas. Larger values will place in the center of aisles more exactly (if non-`FREE` cost potential field exists) but take slightly longer to compute. To optimize for speed, a value of 1.0 is reasonable. A reasonable tradeoff value is 2.0. A value of 0.0 effective disables steering away from obstacles and acts like a naive binary search A*.
      angle_quantization_bins: 64         #用于 SE2 搜索的角度箱数量。这可以是任何偶数，但好的基线是 64 或 72（以 5 度为增量）
      # For Hybrid/Lattice nodes: Number of angle bins for search, must be 1 for 2D node (no angle search)
      analytic_expansion_ratio: 4.0       #规划器将尝试以与该值和最小启发式方法成比例的频率完成分析扩展。
      # For Hybrid/Lattice nodes: The ratio to attempt analytic expansions during search for final approach.
      minimum_turning_radius: 0.4        #最小转弯半径
      # For Hybrid/Lattice nodes: minimum turning radius in m of path / vehicle
      reverse_penalty: 1.0                #如果反向搜索，则对 SE2 节点应用启发式惩罚。
      # For Reeds-Shepp model: penalty to apply if motion is reversing, must be => 1
      change_penalty: 1.5                #如果在搜索中改变方向（例如从左到右），则对 SE2 节点应用启发式惩罚。
      # For Hybrid nodes: penalty to apply if motion is changing directions, must be >= 0
      non_straight_penalty: 8.50          #如果在非直线方向上搜索，则对 SE2 节点应用启发式惩罚。
      # For Hybrid nodes: penalty to apply if motion is non-straight, must be => 1
      cost_penalty: 1.7                   #应用于 SE2 节点的姿势成本的启发式惩罚。
      # For Hybrid nodes: penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
      lookup_table_size: 20.0               #距离窗口的缓存大小
      # For Hybrid nodes: Size of the dubin/reeds-sheep distance window to cache, in meters.
      cache_obstacle_heuristic: True        #缓存障碍启发式，默认False
      # For Hybrid nodes: Cache the obstacle map dynamic programming distance expansion heuristic between subsiquent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.     
      smoother:
        max_iterations: 2000 #平滑器平滑路径的最大迭代次数，以限制潜在的计算。
        # max_iterations: 1000 #平滑器平滑路径的最大迭代次数，以限制潜在的计算。
        w_smooth: 0.5 #应用于平滑数据点的平滑权重
        w_data: 0.1 #应用权重平滑以保留原始数据信息
        # w_smooth: 0.3 #应用于平滑数据点的平滑权重
        # w_data: 0.2 #应用权重平滑以保留原始数据信息
        tolerance: 1.0e-12 #终止平滑会话的参数容差变化量
        # tolerance: 1.0e-10 #终止平滑会话的参数容差变化量
#参数参考：https://docs.nav2.org/configuration/packages/smac/configuring-smac-hybrid.html?highlight=nav2_smac_planner      
 
planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

smoother_server:
  ros__parameters:
    use_sim_time: True
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10 #TF transform tolerance.
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw           #用于在局部代价地图上进行碰撞检查的原始代价地图主题。
    footprint_topic: local_costmap/published_footprint #局部代价地图框架中的足迹主题。
    cycle_frequency: 10.0 #运行行为插件的频率。
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"] #插件包括：{“旋转”、“备份”、“前进”、“等待”}
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    global_frame: odom
    robot_base_frame: base_footprint
    transform_tolerance: 0.1 #TF 变换容差
    use_sim_time: True
    simulate_ahead_time: 5.0 #提前模拟
    max_rotational_vel: 1.0  #最大旋转速度（弧度/秒）
    min_rotational_vel: 0.0 #最小旋转速度（弧度/秒）
    rotational_acc_lim: 0.3  #最大旋转加速度（rad/s^2）

robot_state_publisher:
  ros__parameters:
    use_sim_time: True

waypoint_follower:
  ros__parameters:
    loop_rate: 20 #循环速率
    stop_on_failure: True #如果单个航点失败，是否使操作任务失败。如果为 false，将继续到下一个航点。
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200 #机器人到达每个航点后休眠/等待的时间（以毫秒为单位）
#waypoint_follower 参数参考
#https://docs.nav2.org/configuration/packages/configuring-waypoint-follower.html?highlight=stop_on_failure
