global_costmap:
  ros__parameters:
    footprint: [[-0.305, -0.18], [-0.305, 0.18], [0.305, 0.18], [0.305, -0.18]]
    footprint_padding: 0.01
    transform_tolerance: 0.5
    update_frequency: 0.6
    publish_frequency: 1.0

    global_frame: map
    robot_base_frame: base_footprint
    resolution: 0.1

    rolling_window: true
    width: 80.0
    height: 90.0
    track_unknown_space: false

    plugins:
      - {name: static, type: "costmap_2d::StaticLayer"}
      - {name: sensor, type: "costmap_2d::ObstacleLayer"}
      - {name: inflation, type: "costmap_2d::InflationLayer"}

    static:
      map_topic: /map
      subscribe_to_updates: true

    sensor:
      observation_sources: laser_scan_sensor
      laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

    inflation:
      inflation_radius: 0.01
      cost_scaling_factor: 80.0